name: flutter_radec_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^3.1.1
  firebase_core: ^1.4.0
  firebase_database: ^8.0.0
  firebase_storage: ^10.0.3
  fluttertoast: ^8.0.8
  image_picker: ^0.8.6+4
  ndialog: ^4.1.0
  firebase_core_platform_interface: 4.5.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
